### ISSUE TITLE
[packaging]: set Path env default to include: /usr/games/

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#121]

**Comment by jriddell** [comment]
my desktop has:
>cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"

but I've no idea what makes that file

**Comment by mgraesslin** [comment]
I just opened konsole on the phone:
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by jriddell** [comment]
I believe you!  There's something which overwrites /etc/environment in touch so I guess I'll just add it to our setup package to fix it

**Comment by jriddell** [comment]
added to plasma-phone-settings, will be updated when mobile ci reappears

**Comment by jriddell** [comment]
building...

**Comment by star-buck** [comment]
IMG 120: still not working with latest plsma-phone-settings, $PATH:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by apachelogger** [comment]
@jriddell PATH comes from /etc/login.defs initially, so unless something manually mangles the PATH after login (e.g. sets it explicitly to the limited version) this is either a problem with simplelogin/pam not loading login.defs correctly or login.defs being wrong.

I feel like we had the same problem with sddm a while ago and it turned out to be the PAMs IIRC

**Comment by jriddell** [comment]
just added to /etc/environment for now
