### ISSUE TITLE
audio on nexus 5x (bullhead)

### ISSUE THREAD

**Issue by bhush9** [plasma-mobile/mobster#265]
- [x] new system img with audio_policy.conf ( 20171210-113748 )
- [x] new rootfs with pulseaudio configuration

**Comment by bhush9** [comment]
This has been done now. (rootfs version : `20171210-140255`)

**Comment by star-buck** [comment]
I can reflash latest img to get sound now?

**Comment by bhush9** [comment]
Yes, you can..  at least oh it's gorgeous works now! ;-)

**Comment by star-buck** [comment]
Ah nice to get that back ;)

Any chance for a music player ans some creative common tunes?


On Dec 10, 2017 7:18 AM, "Bhushan Shah" <notifications@github.com> wrote:

Yes, you can.. at least oh it's gorgeous works now! ;-)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/blue-systems/pm-neon/issues/265#issuecomment-350555363>,
or mute the thread

**Comment by bhush9** [comment]
I'll experiment on currently available music players once issue #264 is resolved, there are some stability issues I want to focus on first.

**Comment by bhush9** [comment]
just as FYI, there was bug in flash script, which made it re-use the old system.img if present, it is fixed in latest git master : https://github.com/plasma-phone-packaging/pm-flashtool/commit/75e195b27da3cad8bb0e4f9ea4a545dfb1094d0e

So if audio don't work, it might be that bug.
