### ISSUE TITLE
fix 20 seconds delay between start sound and login screen coming up

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#270]

**Comment by bhush9** [comment]
For some reason, for first few seconds, kwin fails to initialize disaplay it seems from initial investigation, I will try to figure this out.

**Comment by bhush9** [comment]
I investigated it more and I've at least solved the initial delay before starting android container locally, but kwin_wayland still takes time to render, I am not sure what is wrong about that yet, I will investigate more tomorrow

**Comment by bhush9** [comment]
`20180124-113114` image have this fixed.

random note: instead of lockscreen, it will boot to plasmashell as lockscreen on startup is disabled, based on feedback in matrix and telegram lockscreen confuses people since they have not enabled it.. this haven't disabled lockscreen completely but just on startup..

**Comment by star-buck** [comment]
hmm, now the desktop appear first, then 5-10 seconds later the login screen overlays it?
