### ISSUE TITLE
mycroft: provide necessary packages for n5x, that can then be either pre-installed or installed manually through synaptic/discover

### ISSUE THREAD

**Issue by star-buck** [plasma-mobile/mobster#290]
provide packages for 
- mycroft-core: https://github.com/MycroftAi/mycroft-core
- mycroft-plasma-mobile: https://cgit.kde.org/scratch/adityam/plasma-mycroft-mobile.git/

**Comment by star-buck** [comment]
plasma-enabled skills are currently outside official mycroft repos, so cannot installed via voice command, e.g. food-wizard:
https://github.com/AIIX/food-wizard

to manually install:
cd mycroft-core, source .venv/bin/activate and then msm install repourl
![manual-installation-of-skills](https://user-images.githubusercontent.com/840070/44479550-34940100-a641-11e8-84b3-ebe546431ba1.jpg)

**Comment by hsitter** [comment]
https://github.com/plasma-phone-packaging/mycroft-core
https://github.com/plasma-phone-packaging/plasma-mycroft-mobile

NB: since the (desktop) plasmoid by default looks in ~/mycroft-core for the mycroft install, it's easiest to `ln -s /opt/mycroft $HOME/mycroft-core` to get a functional setup.

Also, this stuff is geared towards the mobile system because of how mycroft-core continues to not really be usable in a multi-user fashion without requiring modifications. Specifically before installing the mycroft-core deb a user `phablet` should exist on the system, this user will be owner of /opt/mycroft and /var/log/mycroft. That is the default user on the phone image..

On my system this works for the most part. A lot of the mycroft core skills are however not working properly because skills fail to import mycroft python modules. I entirely lack the domain knowledge to debug this properly.

e.g. `hey mycroft, install $skill`

Asking for the weather works though.

**Comment by AIIX** [comment]
All default skills come with their own requirements.txt which have the python dependencies required for the skill to work Mycroft Skills Manager (msm) installs those dependencies in the virtual environment (at least on the git version) where the skills look for the dependency, all default skills are installed generally when the user first time starts up mycroft and msm is responsible for handling the skill dependency installation post that or anytime someone installs a skill.

https://github.com/MycroftAI/mycroft-skills-manager
